[package]
name = "rv-audio"
version.workspace = true
edition.workspace = true

[features]
default = []
opus-codec = ["dep:opus"]
rnnoise-denoise = ["dep:nnnoiseless"]

[dependencies]
opus = { version = "0.3", optional = true }
nnnoiseless = { version = "0.5", optional = true }

[dev-dependencies]
rand = "0.8"
