[package]
name = "rv-crypto"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["lib", "staticlib", "cdylib"]

[dependencies]
x25519-dalek = { version = "2", features = ["static_secrets"] }
hkdf = "0.13"
sha2 = "0.10"
aes-gcm = "0.10"
rand = "0.8"
zeroize = { version = "1", features = ["derive"] }

[dev-dependencies]
hex = "0.4"
